export const KO_VERSION_IDS = new Set(["gae", "han", "sae"]);

export const KO_TRANSLATIONS = [
	{
		identifier: "gae",
		name: "개역개정",
		language: "Korean",
		language_code: "ko",
		license: "",
	},
	{
		identifier: "han",
		name: "개역한글",
		language: "Korean",
		language_code: "ko",
		license: "",
	},
	{
		identifier: "sae",
		name: "표준새번역",
		language: "Korean",
		language_code: "ko",
		license: "",
	},
];

// Same IDs as the external Bible API (uppercase) with Korean names
export const KO_BOOKS = [
	{ id: "GEN", name: "창세기" },
	{ id: "EXO", name: "출애굽기" },
	{ id: "LEV", name: "레위기" },
	{ id: "NUM", name: "민수기" },
	{ id: "DEU", name: "신명기" },
	{ id: "JOS", name: "여호수아" },
	{ id: "JDG", name: "사사기" },
	{ id: "RUT", name: "룻기" },
	{ id: "1SA", name: "사무엘상" },
	{ id: "2SA", name: "사무엘하" },
	{ id: "1KI", name: "열왕기상" },
	{ id: "2KI", name: "열왕기하" },
	{ id: "1CH", name: "역대상" },
	{ id: "2CH", name: "역대하" },
	{ id: "EZR", name: "에스라" },
	{ id: "NEH", name: "느헤미야" },
	{ id: "EST", name: "에스더" },
	{ id: "JOB", name: "욥기" },
	{ id: "PSA", name: "시편" },
	{ id: "PRO", name: "잠언" },
	{ id: "ECC", name: "전도서" },
	{ id: "SNG", name: "아가" },
	{ id: "ISA", name: "이사야" },
	{ id: "JER", name: "예레미야" },
	{ id: "LAM", name: "예레미야애가" },
	{ id: "EZK", name: "에스겔" },
	{ id: "DAN", name: "다니엘" },
	{ id: "HOS", name: "호세아" },
	{ id: "JOL", name: "요엘" },
	{ id: "AMO", name: "아모스" },
	{ id: "OBA", name: "오바댜" },
	{ id: "JON", name: "요나" },
	{ id: "MIC", name: "미가" },
	{ id: "NAM", name: "나훔" },
	{ id: "HAB", name: "하박국" },
	{ id: "ZEP", name: "스바냐" },
	{ id: "HAG", name: "학개" },
	{ id: "ZEC", name: "스가랴" },
	{ id: "MAL", name: "말라기" },
	{ id: "MAT", name: "마태복음" },
	{ id: "MRK", name: "마가복음" },
	{ id: "LUK", name: "누가복음" },
	{ id: "JHN", name: "요한복음" },
	{ id: "ACT", name: "사도행전" },
	{ id: "ROM", name: "로마서" },
	{ id: "1CO", name: "고린도전서" },
	{ id: "2CO", name: "고린도후서" },
	{ id: "GAL", name: "갈라디아서" },
	{ id: "EPH", name: "에베소서" },
	{ id: "PHP", name: "빌립보서" },
	{ id: "COL", name: "골로새서" },
	{ id: "1TH", name: "데살로니가전서" },
	{ id: "2TH", name: "데살로니가후서" },
	{ id: "1TI", name: "디모데전서" },
	{ id: "2TI", name: "디모데후서" },
	{ id: "TIT", name: "디도서" },
	{ id: "PHM", name: "빌레몬서" },
	{ id: "HEB", name: "히브리서" },
	{ id: "JAS", name: "야고보서" },
	{ id: "1PE", name: "베드로전서" },
	{ id: "2PE", name: "베드로후서" },
	{ id: "1JN", name: "요한일서" },
	{ id: "2JN", name: "요한이서" },
	{ id: "3JN", name: "요한삼서" },
	{ id: "JUD", name: "유다서" },
	{ id: "REV", name: "요한계시록" },
];
